apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "simplenodeservice-team04-qa"
  title: "simplenodeservice-team04-qa"
  description: "Template for the simplenodeservice owned and operated by team04 in environment qa"
  annotations:
    backstage.io/techdocs-ref: dir:.
    # Not working
    'backstage.io/kubernetes-label-selector': 'app.kubernetes.io/name=userinterface'
    'backstage.io/kubernetes-namespace': 'simplenodeservice-team04-qa'
    argocd/app-name: simplenodeservice-team04-qa
  links:
    - url: https://github.com/wilDynatrace/enablement-openpipeline-segments-iam.git
      title: Github Repo
      icon: github
    - url: https://curly-goldfish-g4qp4xjr4qxxfpwgw-80.app.github.dev/simplenodeservice-team04-qa
      title: "Browse Application"
      icon: subject
    - title: View in ArgoCD
      icon: catalog
      url: https://curly-goldfish-g4qp4xjr4qxxfpwgw-30100.app.github.dev/applications/argocd/simplenodeservice-team04-qa
    - title: View in Dynatrace
      icon: catalog
      url: https://sup9183h.sprint.apps.dynatracelabs.com
    - url: https://community.dynatrace.com
      title: Dynatrace community
      icon: dashboard
spec:
  type: website
  owner: team04
  lifecycle: qa
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: "team04"
  description: Group for application team team04
spec:
  type: business-unit
  profile:
    displayName: Team 04
    email: team04@example.com
    picture: https://example.com/staff/jenny-with-party-hat.jpeg
  parent: applications
  children: []
#   members: [jdoe]
